name: Build linux Qt6

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch'
        required: true
        default: 'master'

jobs:
  build_linux:

    runs-on: ubuntu-latest

    steps:

    # Install uuid-dev
    - name: Install uuid-dev
      run: |
           sudo apt update
           sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install uuid-dev
      shell: bash

    # Install Java 11
    - name: Install Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    # Install cmake version v3.24.x
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: 'v3.24.x'

    # Checkout dlt-viewer's revision v2.25.0
    - name: Checkout of the dlt-viewer
      uses: actions/checkout@v3
      with:
        repository: GENIVI/dlt-viewer
        ref: v2.25.0

    # Checkout project's revision, which is pushed
    - name: Checkout of the ${{ github.event.repository.name }}
      uses: actions/checkout@v3
      with:
        repository: svlad-90/${{ github.event.repository.name }}
        path: ./plugin/${{ github.event.repository.name }}
        ref: ${{ github.ref }}

    # Adjust dlt-viewer's CMake file to sub-include the plugin
    - name: Patch dlt-viewer's CMakeLists.txt
      run: echo 'add_subdirectory(${{ github.event.repository.name }}/dltmessageanalyzerplugin/src)' >> CMakeLists.txt
      shell: bash
      working-directory: ./plugin

    # Install Qt6
    - name: Install Qt6
      uses: jurplel/install-qt-action@v3
      with:
         version: 6.5.0
         target: desktop
         host: linux
         dir: ${{ github.workspace }}/Qt6
         cache: true
         modules: 'qtserialport'

    # Create build directory
    - name: Creation of the "../build" directory
      run: mkdir ../build
      shell: bash
      working-directory: ./

    # CMake execution
    - name: CMake
      run: cmake ../${{ github.event.repository.name }}
      shell: bash
      working-directory: ../build

    # Build of the project
    - name: Make
      run: make -j8
      shell: bash
      working-directory: ../build
